---
  -
    url: "api/defaults"
  - 
    url: "api/statuscode"
    method: GET
    status-code: 502
    content: |
      {
        "controller": "Fake",
        "action": "{statusCode}"
      }
  - 
    url: "api/multiplemethods"
    methods: [ GET, POST ]
    content: |
      {
        "controller": "Fake",
        "action": "{statusCode}"
      }
  - 
    url: "api/match1/\\d+"
    content: "match1"
